version: "3"

services:
  db:
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    volumes:
      - redis:/var/lib/redis
  app:
    image: pujas.live_production-app
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c "npm run sync && npm start"
    volumes: []
    ports:
      - "127.0.0.1:3001:3000"
  worker:
    image: pujas.live_production-app
    restart: unless-stopped
    command: npm run worker
    volumes: []

volumes:
  pgdata:
  redis:
